# Generated by Django 5.0.6 on 2024-05-22 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workers', '0004_alter_worker_ssn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_supervisor', models.BooleanField(default=False)),
                ('date_joined', models.DateField()),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Workgroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('members', models.ManyToManyField(through='workgroups.Membership', to='workers.worker')),
                ('sub_groups', models.ManyToManyField(blank=True, null=True, to='workgroups.workgroup')),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='workgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workgroups.workgroup'),
        ),
    ]
