# Generated by Django 5.0.6 on 2024-05-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workgroups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workgroup',
            name='sub_groups',
        ),
        migrations.AddField(
            model_name='workgroup',
            name='subgroups',
            field=models.ManyToManyField(blank=True, to='workgroups.workgroup'),
        ),
    ]
