# Generated by Django 5.0.6 on 2024-05-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='type',
            field=models.CharField(choices=[('EMP', 'Employee'), ('FRL', 'Freelancer')], default='EMP', max_length=4),
        ),
    ]
