# Generated by Django 5.0.6 on 2024-05-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_worker_ssn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='ssn',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Social Security Number'),
        ),
    ]
